services:
  - type: web
    name: trunklogistics-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm ci && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: trunklogistics-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://truck-logistics-mvp.vercel.app
      - key: FRONTEND_URL
        value: https://truck-logistics-mvp.vercel.app

databases:
  - name: trunklogistics-db
    databaseName: trunklogistics
    user: postgres
    region: oregon
    plan: free