#!/bin/bash

# SendGrid Sender Verification Checker
# This script helps verify your SendGrid configuration

echo "🔐 TruckLogistics - SendGrid Configuration Checker"
echo "=================================================="
echo ""

# Expected configuration
EXPECTED_EMAIL_SERVICE="sendgrid"
EXPECTED_EMAIL_FROM="korichiaymen27@gmail.com"
EXPECTED_EMAIL_FROM_NAME="TruckLogistics"
EXPECTED_CLIENT_URL="https://truck-logistics-mvp.vercel.app"

echo "📋 Expected Production Configuration:"
echo "---------------------------------------------------"
echo "EMAIL_SERVICE:     $EXPECTED_EMAIL_SERVICE"
echo "EMAIL_FROM:        $EXPECTED_EMAIL_FROM"
echo "EMAIL_FROM_NAME:   $EXPECTED_EMAIL_FROM_NAME"
echo "CLIENT_URL:        $EXPECTED_CLIENT_URL"
echo "SENDGRID_API_KEY:  SG.xxx... (should be set)"
echo ""

echo "⚠️  CRITICAL REQUIREMENT:"
echo "---------------------------------------------------"
echo "The sender email ($EXPECTED_EMAIL_FROM)"
echo "MUST be verified in SendGrid before emails will send!"
echo ""

echo "📝 Verification Steps:"
echo "---------------------------------------------------"
echo "1. Go to: https://app.sendgrid.com/settings/sender_auth/senders"
echo "2. Click 'Create New Sender' (if not already added)"
echo "3. Fill in the form with:"
echo "   - From Email: $EXPECTED_EMAIL_FROM"
echo "   - From Name: $EXPECTED_EMAIL_FROM_NAME"
echo "   - Reply To: $EXPECTED_EMAIL_FROM"
echo "4. Click 'Create'"
echo "5. Check your Gmail inbox ($EXPECTED_EMAIL_FROM)"
echo "6. Click the verification link in the email from SendGrid"
echo "7. Confirm you see a GREEN CHECKMARK in SendGrid dashboard"
echo ""

echo "✅ After Verification, Test Here:"
echo "---------------------------------------------------"
echo "Frontend: $EXPECTED_CLIENT_URL/forgot-password"
echo "SendGrid Activity: https://app.sendgrid.com/activity"
echo "Render Logs: https://dashboard.render.com"
echo ""

echo "🔍 How to Check if Sender is Verified:"
echo "---------------------------------------------------"
echo "1. Go to: https://app.sendgrid.com/settings/sender_auth/senders"
echo "2. Look for: $EXPECTED_EMAIL_FROM"
echo "3. Status should show: 'Verified' with green checkmark ✅"
echo "4. If status is 'Pending' → Check Gmail for verification email"
echo "5. If not listed → Create new sender and verify"
echo ""

echo "📊 SendGrid Activity Feed:"
echo "---------------------------------------------------"
echo "URL: https://app.sendgrid.com/activity"
echo ""
echo "Look for these statuses:"
echo "  ✅ Processed - Email accepted by SendGrid"
echo "  ✅ Delivered - Email delivered to recipient"
echo "  ❌ Dropped - Usually means sender not verified"
echo "  ❌ Bounced - Recipient email invalid"
echo ""

echo "🐛 Troubleshooting:"
echo "---------------------------------------------------"
echo "If password reset still doesn't work after verification:"
echo ""
echo "1. Check Render environment variables match above"
echo "2. Restart your Render service after any env changes"
echo "3. Check SendGrid Activity feed for email status"
echo "4. Check Render logs for error messages"
echo "5. Verify SENDGRID_API_KEY is correct and active"
echo ""

echo "📞 Support Links:"
echo "---------------------------------------------------"
echo "SendGrid Sender Auth: https://app.sendgrid.com/settings/sender_auth"
echo "SendGrid Activity:    https://app.sendgrid.com/activity"
echo "SendGrid API Keys:    https://app.sendgrid.com/settings/api_keys"
echo "Render Dashboard:     https://dashboard.render.com"
echo ""

echo "✨ Quick Test After Setup:"
echo "---------------------------------------------------"
echo "1. Ensure sender is verified (green checkmark)"
echo "2. Go to: $EXPECTED_CLIENT_URL/forgot-password"
echo "3. Enter your email address"
echo "4. Check inbox and spam folder"
echo "5. Check SendGrid Activity feed"
echo "6. Check Render logs"
echo ""

echo "=================================================="
echo "Setup complete! Follow the steps above to verify."
echo "=================================================="
